# Generated by Django 2.1.2 on 2018-10-17 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181013_1915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_auto_20181017_1642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'listing')},
        ),
    ]
